[build]
default-target = "armv7-unknown-linux-gnueabihf" 
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install libpulse-dev:$CROSS_DEB_ARCH"
] 